# backend/render.yaml
services:
  - type: web
    name: analise-inteligente-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_URL
        value: https://insightstextanalysis.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: analise_db
          property: connectionString

databases:
  - name: analise_db
    plan: free
    databaseName: analise_inteligente
    user: analise_user